Minor bug fixes
Replaced most 'echo -e' with 'printf' for compatibility

diff --git a/zeropkg b/zeropkg
--- a/zeropkg
+++ b/zeropkg
@@ -9,7 +9,7 @@ bold="\033[1m"
 reset="\033[0m"
 # arguments
 config="/etc/zeropkg.cfg"
-source "$config"
+. "$config"
 command="${1}"
 arg="${2}"
 version="${blue}zeropkg 001${reset}"
@@ -22,51 +22,51 @@ fi
 }
 check_file_exists() {
 if [ ! -f "$1" ]; then
-echo -e "${red}File not found: $1${reset}"
+printf "${red}File not found: $1${reset}"
 exit 1
 fi
 }
 usage(){
-echo -e "Usage: ${blue}${0}${reset} ${yellow}[-i package_archive] [-r package] [-d url] [-l] [-h] [-v] [-m package] [-p package] [-g]${reset}"
-echo -e "  ${yellow}-i${reset} Install a package. (from an archive)"
-echo -e "  ${yellow}-r${reset} Remove a package."
-echo -e "  ${yellow}-l${reset} List installed packages."
-echo -e "  ${yellow}-h${reset} Display this help message."
-echo -e "  ${yellow}-d${reset} Download a package. (needs url)"
-echo -e "  ${yellow}-v${reset} Package manager version."
-echo -e "  ${yellow}-m${reset} Display package metadata."
-echo -e "  ${yellow}-p${reset} Purge a package. (deletes all configuration and scripts related)"
-echo -e "  ${yellow}-g${reset} Generate a default config file. (/etc/zeropkg.cfg)"
+printf "Usage: ${blue}${0}${reset} ${yellow}[-i package_archive] [-r package] [-d url] [-l] [-h] [-v] [-m package] [-p package] [-g]${reset}"
+printf "  ${yellow}-i${reset} Install a package. (from an archive)"
+printf "  ${yellow}-r${reset} Remove a package."
+printf "  ${yellow}-l${reset} List installed packages."
+printf "  ${yellow}-h${reset} Display this help message."
+printf "  ${yellow}-d${reset} Download a package. (needs url)"
+printf "  ${yellow}-v${reset} Package manager version."
+printf "  ${yellow}-m${reset} Display package metadata."
+printf "  ${yellow}-p${reset} Purge a package. (deletes all configuration and scripts related)"
+printf "  ${yellow}-g${reset} Generate a default config file. (/etc/zeropkg.cfg)"
 }
 if [ -z "$command" ]; then
 usage
 exit 1
 fi
 if [ "$UID" -ne "0" ]; then
-echo "${red}Run as root!${reset}"
+printf "${red}Run as root!${reset}"
 exit 1
 fi
 download_package(){ # download with curl
 check_arg
 filename=$(basename "$arg")
 name="${filename%%.*}" # i admit this is reddit
-echo -e "${yellow}Downloading ${arg} with curl...${reset}"
+printf "${yellow}Downloading ${arg} with curl...${reset}"
 mkdir -p "${DOWNLOAD_DIR}/${name}"
 curl -Lo "${DOWNLOAD_DIR}/${name}/${filename}" "$arg"
 if [ "$?" -eq 0 ]; then
-echo -e "${green}Downloaded to /$DOWNLOAD_DIR/$name/ (config location)...${reset}"
-echo -e "${yellow}Run '$0 -i <archive>' to install!${reset}"
+printf "${green}Downloaded to /$DOWNLOAD_DIR/$name/ (config location)...${reset}"
+printf "${yellow}Run '$0 -i <archive>' to install!${reset}"
 else
-echo -e "${red}Download failed: exit status: $?, Read the output for more information...${reset}"
+printf "${red}Download failed: exit status: $?, Read the output for more information...${reset}"
 fi
 }
 install_package(){ # install from archive
 check_arg
-echo -e "${yellow}Installing ${arg} (Make sure you are in the same directory as the archive...)${reset}"
+printf "${yellow}Installing ${arg} (Make sure you are in the same directory as the archive...)${reset}"
 filename=$(basename "$arg" .tar.gz)
 tar -xzf "${arg}" -C "${DOWNLOAD_DIR}"
 if [ $? -ne 0 ]; then
-echo -e "${red}TAR failed: exit status: $?, Read the output for more information...${reset}"
+printf "${red}TAR failed: exit status: $?, Read the output for more information...${reset}"
 exit 1
 fi
 check_file_exists "${DOWNLOAD_DIR}/$filename/name"
@@ -75,7 +75,7 @@ echo $pkg_name >> $INSTALL_LOG
 if [ -f "${DOWNLOAD_DIR}/${filename}/build" ]; then
 sh "${DOWNLOAD_DIR}/$filename/build"
 if [ $? -ne 0 ]; then
-echo -e "${red}Build script failed, exiting..${reset}"
+printf "${red}Build script failed, exiting..${reset}"
 exit 1
 fi
 fi
@@ -83,16 +83,16 @@ if [ -f "${DOWNLOAD_DIR}/${filename}/remove" ]; then
 mkdir -p "${REMOVE_SCRIPTS}/$pkg_name"
 mv -f "${DOWNLOAD_DIR}/${filename}/remove" "${REMOVE_SCRIPTS}/${pkg_name}/"
 else
-echo -e "${red}Remove script does not exist, exiting...${reset}"
+printf "${red}Remove script does not exist, exiting...${reset}"
 exit 1
 fi
 if [ -f "${DOWNLOAD_DIR}/${filename}/metadata.txt" ]; then
 mkdir -p "$METADATA_FILES/$pkg_name/"
 mv "${DOWNLOAD_DIR}/${filename}/metadata.txt" "$METADATA_FILES/$pkg_name/"
 else
-echo -e "${red}Package metadata file not found, ignoring...${reset}"
+printf "${red}Package metadata file not found, ignoring... (this could break removal) ${reset}"
 fi
-echo -e "${yellow}Package successfully installed!${reset}"
+printf "${yellow}Package successfully installed!${reset}"
 }
 remove_package(){ # remove package
 check_arg
@@ -109,13 +109,13 @@ check_file_exists "$METADATA_FILES/$arg/metadata.txt"
 cat "$METADATA_FILES/$arg/metadata.txt"
 }
 purge_package(){ # purge package (remove but deletes everything related)
-echo -e "${yellow}Purging $DOWNLOAD_DIR files related to $arg${reset}"
+printf "${yellow}Purging $DOWNLOAD_DIR files related to $arg${reset}"
 rm -rf "$DOWNLOAD_DIR/$arg"
 rm -rf "$DOWNLOAD_DIR/$arg.tar.gz"
-echo -e "${yellow}Purging $METADATA_FILES files related to $arg${reset}"
+printf "${yellow}Purging $METADATA_FILES files related to $arg${reset}"
 check_file_exists "$METADATA_FILES/$arg/metadata.txt"
 rm -rf "$METADATA_FILES/$arg"
-echo -e "${yellow}Purging $REMOVE_SCRIPTS files related to $arg${reset}"
+printf "${yellow}Purging $REMOVE_SCRIPTS files related to $arg${reset}"
 check_file_exists "$REMOVE_SCRIPTS/$arg/remove"
 sh "$REMOVE_SCRIPTS/$arg/remove"
 rm -rf "$REMOVE_SCRIPTS/$arg"
@@ -123,7 +123,7 @@ sed -i "/$arg/d" $INSTALL_LOG
 }
 generate_config(){
 echo -e "# DEFAULT CONFIGURATION\nDOWNLOAD_DIR=/tmp/zeropkg\nINSTALL_LOG=/etc/pkg-install.log\nREMOVE_SCRIPTS=/var/zeropkg/remove_scripts\nMETADATA_FILES=/var/zeropkg/metadata" > "/etc/zeropkg.cfg"
-echo -e "${yellow}Generated config...${reset}"
+printf "${yellow}Generated config...${reset}"
 }
 case "$command" in
 -d) download_package ;;
@@ -137,4 +137,3 @@ case "$command" in
 -g) generate_config ;;
 *) usage ;;
 esac
-
