Fixed bugs
Forgot to add '\n' when using printf... oops

diff --git a/zeropkg b/zeropkg
--- a/zeropkg
+++ b/zeropkg
@@ -22,51 +22,51 @@ fi
 }
 check_file_exists() {
 if [ ! -f "$1" ]; then
-printf "${red}File not found: $1${reset}"
+printf "${red}File not found: $1${reset}\n"
 exit 1
 fi
 }
 usage(){
-printf "Usage: ${blue}${0}${reset} ${yellow}[-i package_archive] [-r package] [-d url] [-l] [-h] [-v] [-m package] [-p package] [-g]${reset}"
-printf "  ${yellow}-i${reset} Install a package. (from an archive)"
-printf "  ${yellow}-r${reset} Remove a package."
-printf "  ${yellow}-l${reset} List installed packages."
-printf "  ${yellow}-h${reset} Display this help message."
-printf "  ${yellow}-d${reset} Download a package. (needs url)"
-printf "  ${yellow}-v${reset} Package manager version."
-printf "  ${yellow}-m${reset} Display package metadata."
-printf "  ${yellow}-p${reset} Purge a package. (deletes all configuration and scripts related)"
-printf "  ${yellow}-g${reset} Generate a default config file. (/etc/zeropkg.cfg)"
+printf "Usage: ${blue}${0}${reset} ${yellow}[-i package_archive] [-r package] [-d url] [-l] [-h] [-v] [-m package] [-p package] [-g]${reset}\n"
+printf "  ${yellow}-i${reset} Install a package. (from an archive)\n"
+printf "  ${yellow}-r${reset} Remove a package.\n"
+printf "  ${yellow}-l${reset} List installed packages.\n"
+printf "  ${yellow}-h${reset} Display this help message.\n"
+printf "  ${yellow}-d${reset} Download a package. (needs url)\n"
+printf "  ${yellow}-v${reset} Package manager version.\n"
+printf "  ${yellow}-m${reset} Display package metadata.\n"
+printf "  ${yellow}-p${reset} Purge a package. (deletes all configuration and scripts related)\n"
+printf "  ${yellow}-g${reset} Generate a default config file. (/etc/zeropkg.cfg)\n"
 }
 if [ -z "$command" ]; then
 usage
 exit 1
 fi
 if [ "$UID" -ne "0" ]; then
-printf "${red}Run as root!${reset}"
+printf "${red}Run as root!${reset}\n"
 exit 1
 fi
 download_package(){ # download with curl
 check_arg
 filename=$(basename "$arg")
 name="${filename%%.*}" # i admit this is reddit
-printf "${yellow}Downloading ${arg} with curl...${reset}"
+printf "${yellow}Downloading ${arg} with curl...${reset}\n"
 mkdir -p "${DOWNLOAD_DIR}/${name}"
 curl -Lo "${DOWNLOAD_DIR}/${name}/${filename}" "$arg"
 if [ "$?" -eq 0 ]; then
-printf "${green}Downloaded to /$DOWNLOAD_DIR/$name/ (config location)...${reset}"
-printf "${yellow}Run '$0 -i <archive>' to install!${reset}"
+printf "${green}Downloaded to /$DOWNLOAD_DIR/$name/ (config location)...${reset}\n"
+printf "${yellow}Run '$0 -i <archive>' to install!${reset}\n"
 else
-printf "${red}Download failed: exit status: $?, Read the output for more information...${reset}"
+printf "${red}Download failed: exit status: $?, Read the output for more information...${reset}\n"
 fi
 }
 install_package(){ # install from archive
 check_arg
-printf "${yellow}Installing ${arg} (Make sure you are in the same directory as the archive...)${reset}"
+printf "${yellow}Installing ${arg}${reset}\n"
 filename=$(basename "$arg" .tar.gz)
 tar -xzf "${arg}" -C "${DOWNLOAD_DIR}"
 if [ $? -ne 0 ]; then
-printf "${red}TAR failed: exit status: $?, Read the output for more information...${reset}"
+printf "${red}TAR failed: exit status: $?, Read the output for more information...${reset}\n"
 exit 1
 fi
 check_file_exists "${DOWNLOAD_DIR}/$filename/name"
@@ -75,7 +75,7 @@ echo $pkg_name >> $INSTALL_LOG
 if [ -f "${DOWNLOAD_DIR}/${filename}/build" ]; then
 sh "${DOWNLOAD_DIR}/$filename/build"
 if [ $? -ne 0 ]; then
-printf "${red}Build script failed, exiting..${reset}"
+printf "${red}Build script failed, exiting..${reset}\n"
 exit 1
 fi
 fi
@@ -83,16 +83,16 @@ if [ -f "${DOWNLOAD_DIR}/${filename}/remove" ]; then
 mkdir -p "${REMOVE_SCRIPTS}/$pkg_name"
 mv -f "${DOWNLOAD_DIR}/${filename}/remove" "${REMOVE_SCRIPTS}/${pkg_name}/"
 else
-printf "${red}Remove script does not exist, exiting...${reset}"
+printf "${red}Remove script does not exist, exiting...${reset}\n"
 exit 1
 fi
 if [ -f "${DOWNLOAD_DIR}/${filename}/metadata.txt" ]; then
 mkdir -p "$METADATA_FILES/$pkg_name/"
 mv "${DOWNLOAD_DIR}/${filename}/metadata.txt" "$METADATA_FILES/$pkg_name/"
 else
-printf "${red}Package metadata file not found, ignoring... (this could break removal) ${reset}"
+printf "${red}Package metadata file not found, ignoring... (this could break removal) ${reset}\n"
 fi
-printf "${yellow}Package successfully installed!${reset}"
+printf "${yellow}Package successfully installed!${reset}\n"
 }
 remove_package(){ # remove package
 check_arg
@@ -109,13 +109,13 @@ check_file_exists "$METADATA_FILES/$arg/metadata.txt"
 cat "$METADATA_FILES/$arg/metadata.txt"
 }
 purge_package(){ # purge package (remove but deletes everything related)
-printf "${yellow}Purging $DOWNLOAD_DIR files related to $arg${reset}"
+printf "${yellow}Purging $DOWNLOAD_DIR files related to $arg${reset}\n"
 rm -rf "$DOWNLOAD_DIR/$arg"
 rm -rf "$DOWNLOAD_DIR/$arg.tar.gz"
-printf "${yellow}Purging $METADATA_FILES files related to $arg${reset}"
+printf "${yellow}Purging $METADATA_FILES files related to $arg${reset}\n"
 check_file_exists "$METADATA_FILES/$arg/metadata.txt"
 rm -rf "$METADATA_FILES/$arg"
-printf "${yellow}Purging $REMOVE_SCRIPTS files related to $arg${reset}"
+printf "${yellow}Purging $REMOVE_SCRIPTS files related to $arg${reset}\n"
 check_file_exists "$REMOVE_SCRIPTS/$arg/remove"
 sh "$REMOVE_SCRIPTS/$arg/remove"
 rm -rf "$REMOVE_SCRIPTS/$arg"
@@ -123,7 +123,7 @@ sed -i "/$arg/d" $INSTALL_LOG
 }
 generate_config(){
 echo -e "# DEFAULT CONFIGURATION\nDOWNLOAD_DIR=/tmp/zeropkg\nINSTALL_LOG=/etc/pkg-install.log\nREMOVE_SCRIPTS=/var/zeropkg/remove_scripts\nMETADATA_FILES=/var/zeropkg/metadata" > "/etc/zeropkg.cfg"
-printf "${yellow}Generated config...${reset}"
+printf "${yellow}Generated config...${reset}\n"
 }
 case "$command" in
 -d) download_package ;;
